### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by johnsaigle** [ovanr/webFuzz#1]
Hello,
The BitBucket link in the README doesn't work -- maybe the linked page is private?

**Comment by ovanr** [comment]
Yes, thank you for noticing.
I've updated the README with the new links

**Comment by Azwh123** [comment]
您好，代码里面的memcacheConstants这个模块是您自己定义的嘛，还是从外界导入的呀？因为在运行的时候无法寻找到这个模块。
