### ISSUE TITLE
memcacheConstants module

### ISSUE THREAD

**Issue by Azwh123** [ovanr/webFuzz#2]
"Hello, is the 'memcacheConstants' module defined by yourself or imported from outside? Because it cannot be found during runtime."

**Comment by ovanr** [comment]
Where is this import statement? I don't see it

**Comment by Azwh123** [comment]
when I Run the fuzzer using webFuzz.py.He will give this error message： No module named'memcacheConstants'

**Comment by ovanr** [comment]
Can you provide the complete stack trace?

**Comment by Azwh123** [comment]
"I encountered an error stating that the `memcacheConstants` module is missing when I started to run the fuzzer."
You can look at this picture：
[b3274e4d1b2b65808ff2909051441c4](https://github.com/user-attachments/assets/a07ba958-5a19-41be-8963-568ba2981d7a)

**Comment by ovanr** [comment]
Have you installed all the requirements? 
```
cd webFuzz
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```
Also please provide the full trace not just those 3 lines

**Comment by Azwh123** [comment]
When I execute this command ：pip install -r requirements.txt
[image](https://github.com/user-attachments/assets/f4a66556-29e0-415c-8d50-a8081716a1ff)
During the final installation of dependencies, there will be an error report of version mismatch，You can look at this picture：
[image](https://github.com/user-attachments/assets/ddf0cbb2-54df-4d5e-ae33-7bdf05e80089)

**Comment by ovanr** [comment]
That's strange, in my setup there is no conflict between these packages.
Regardless, I have just pushed an updated requirements.txt that has the newest package versions.
I tested it on a clean setup with python 3.12 and it installs fine.
Hope this works.

**Comment by Azwh123** [comment]
Thank you for updating the requirements.txt, I have successfully installed it
